OneToManyDemo/Models/Auteur.cs
using System.ComponentModel.DataAnnotations;

namespace OneToManyDemo.Models
{
	public class Auteur
	{
		public int AuteurId { get; set; }
		[Required]
		[StringLength(50)]
		public string Naam { get; set; }
        public ICollection<Boek> Boeken { get; set; }//indica la relacion One to many
    }
}

OneToManyDemo/Models/Boek.cs
namespace OneToManyDemo.Models
{
	public class Boek
	{
        public int BoekId { get; set; }
        public string Titel { get; set; }
        public int AuteurId { get; set; }//F key
        public Auteur Auteur { get; set; }
    }
}

OneToManyDemo/Models/ErrorViewModel.cs
namespace OneToManyDemo.Models
{
	public class ErrorViewModel
	{
		public string? RequestId { get; set; }

		public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
	}
}

OneToManyDemo/Models/ViewModels/BoekAuteurViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace OneToManyDemo.Models.ViewModels
{
	public class BoekAuteurViewModel
	{
		[Key]
        public int BoekId { get; set; }
		public string Titel { get; set;}
		[Display(Name = "Autor")]
		public string AuteurNaam { get; set;}
    }
}

OneToManyDemo/Models/ViewModels/BoekenVM1.cs
namespace OneToManyDemo.Models.ViewModels
{
    public class BoekenVM1
    {
        public List<Boek> Boeken { get; set; }
        public List<Auteur> Auteurs { get; set; }
        public int GeselecteerdeAuteurId { get; set; }
    }
}

OneToManyDemo/Models/ViewModels/BoekenViewModel.cs
using Microsoft.EntityFrameworkCore;

namespace OneToManyDemo.Models.ViewModels
{
	[Keyless]
	public class BoekenViewModel
	{
		public List<BoekAuteurViewModel> Boeken { get; set; }
		public List<Auteur> Auteurs { get; set; }
		public int GeselecteerdeAuteurId { get; set; }
		
	}
}

OneToManyDemo/Models/ViewModels/CreateBoekViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace OneToManyDemo.Models.ViewModels
{
    public class CreateBoekViewModel
    {
        [Required(ErrorMessage="Titel is verplicht")]
        public string Titel { get; set; }

        [Required(ErrorMessage = "Auteur is verplicht")]
        [Display(Name = "Auteur")]
        public int AuteurId { get; set; }
        public List<Auteur>? Auteurs { get; set; }
    }
}

OneToManyDemo/Controllers/BoekenController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using OneToManyDemo.Data;
using OneToManyDemo.Models;
using OneToManyDemo.Models.ViewModels;

namespace OneToManyDemo.Controllers
{
	public class BoekenController : Controller
	{
		readonly BoekenDBContext _context;
        public BoekenController(BoekenDBContext dBContext)
        {
            _context = dBContext;
        }
        public async Task<IActionResult> Index()//Para mostrar el contenido de la DB
		{
			var boekAuteurViewModel = _context.Boeks
				.Include(b => b.Auteur)
				.Select(b => new BoekAuteurViewModel
				{
					BoekId = b.BoekId,
					Titel = b.Titel,
					AuteurNaam = b.Auteur.Naam,
				});
			return View(boekAuteurViewModel);
		}

		public async Task<IActionResult> Filters(int? GeselecteerdeAuteurId)
		{
			var auteurs = await _context.Auteurs.ToListAsync();

			IQueryable<Boek> boekenQuery = _context.Boeks.Include(b => b.Auteur);

			if (GeselecteerdeAuteurId.HasValue)
			{
				boekenQuery = boekenQuery.Where(b => b.AuteurId == GeselecteerdeAuteurId);
			}

			var boeken = await boekenQuery.ToListAsync();

			var boekenViewModel = boeken.Select(b => new BoekAuteurViewModel
			{
				BoekId = b.BoekId,
				Titel = b.Titel,
				AuteurNaam = b.Auteur.Naam
			}).ToList();

			var filtersViewModel = new BoekenViewModel
			{
				Auteurs = auteurs,
				Boeken = boekenViewModel,
				GeselecteerdeAuteurId = GeselecteerdeAuteurId ?? 0
			};
			return View(filtersViewModel);
		}

		public async Task<IActionResult> Filter1(int? GeselecteerdeAuteurId)
		{
			var auteurs = await _context.Auteurs.ToListAsync();
			IQueryable<Boek> boekenQuery = _context.Boeks.Include(b => b.Auteur);

			if(GeselecteerdeAuteurId.HasValue && GeselecteerdeAuteurId > 0)
			{
				boekenQuery = boekenQuery.Where(b => b.AuteurId == GeselecteerdeAuteurId.Value);	
			}

			var boeken = await boekenQuery.ToListAsync();
			var viewModel = new BoekenVM1
			{
				Auteurs = auteurs,
				Boeken = boeken,
				GeselecteerdeAuteurId = GeselecteerdeAuteurId ?? 0
			};

			return View(viewModel);
		}

		public async Task<IActionResult> Create()
		{
			//buscar el autor en la lista del dropdown gracias al ViewModel CreateBoekVM
			var auteurs = await _context.Auteurs.ToListAsync();
			var viewmodel = new CreateBoekViewModel
			{
				Auteurs = auteurs
			};
			return View(viewmodel);
		}
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Create(CreateBoekViewModel viewmodel)
		{
			if (!ModelState.IsValid) 
			{
				viewmodel.Auteurs = await _context.Auteurs.ToListAsync();
				return View(viewmodel);
			}
			var newBoek = new Boek
			{
				Titel = viewmodel.Titel,
				AuteurId = viewmodel.AuteurId,
			};
			_context.Boeks.Add(newBoek);
			await _context.SaveChangesAsync();
			return RedirectToAction(nameof(Filters));
		}
		public async Task<IActionResult> Details(int? id)
		{
			if(id == null)
			{
				return NotFound();
			}
			var boek = await _context.Boeks
				.Include(b => b.Auteur)
				.FirstOrDefaultAsync(b => b.BoekId == id);
			if (boek == null)
			{
				return NotFound();
			}
			return View(boek);
		}
	}
}

OneToManyDemo/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using OneToManyDemo.Models;
using System.Diagnostics;

namespace OneToManyDemo.Controllers
{
	public class HomeController : Controller
	{
		private readonly ILogger<HomeController> _logger;

		public HomeController(ILogger<HomeController> logger)
		{
			_logger = logger;
		}

		public IActionResult Index()
		{
			return View();
		}

		public IActionResult Privacy()
		{
			return View();
		}

		[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
		public IActionResult Error()
		{
			return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
		}
	}
}

OneToManyDemo/Views/Boeken/Create.cshtml
@model OneToManyDemo.Models.ViewModels.CreateBoekViewModel

@{
	ViewData["Title"] = "Create";
}

<h2>Nieuw Boek Toevoegen</h2>
<div>
	<form asp-action="Create">
		@* security against cookies bad use *@
		@* @Html.AntiforgeryToken() *@
		<div class="form-group">
			<label asp-for="Titel" class="control-label"></label>
			<input asp-for="Titel" class="form-control"/>
			<span asp-validation-for="Titel" class="text-danger"></span>
		</div>
		<div class="form-group">
			<label asp-for="AuteurId" class="control-label"></label>
			<select asp-for="AuteurId" class="form-control" asp-items=
			"@(new SelectList(Model.Auteurs, "AuteurId", "Naam"))">
			</select>
		</div >
		<div class="form-group">
			<input type="submit" value="Create" class="btn btn-outline-info my-2" />
		</div>
	</form>
</div>

OneToManyDemo/Views/Boeken/Details.cshtml
@model OneToManyDemo.Models.Boek

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Boek</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Titel)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Titel)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Auteur)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Auteur.Naam)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.BoekId">Edit</a> |
    <a asp-action="Filters">Back to List</a>
</div>

OneToManyDemo/Views/Boeken/Filters.cshtml
@model OneToManyDemo.Models.ViewModels.BoekenViewModel

<p>
    <a asp-action="Create" class="btn btn-outline-info">Nieuw Boek Toevoegen</a>
</p>

<form asp-action="Filters" asp-controller="Boeken" method="get">
    <select asp-for="GeselecteerdeAuteurId" asp-items="@(new SelectList(Model.Auteurs,"AuteurId","Naam" ))" class="form-control">
        <option value="">Selecteer een Auteur</option>
    </select>
    <button type="submit" class="btn btn-outline-info my-2">Filter</button>
</form>

<table class="table table-secondary">
    <thead>
        <tr class="table-dark">
            <th>Titel</th>
            <th>Auteur</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var boek in Model.Boeken)
        {
            <tr>
                <td>@boek.Titel</td>
                <td>@boek.AuteurNaam</td>
                <td class="fw-bold">
                @Html.ActionLink("Edit", "Edit", new { id = boek.BoekId })
                @Html.ActionLink("Details", "Details", new {id=boek.BoekId})    
                @Html.ActionLink("Delete", "Delete", new {id=boek.BoekId})</td>    
            </tr>
        }
    </tbody>
    <tfoot>
        <tr>
            <td>
                <i class="fw-bold">Aantal boeken in collectie: @Model.Boeken.Count</i>
            </td>
        </tr>
    </tfoot>
</table>

OneToManyDemo/Views/Boeken/Index.cshtml
@model IEnumerable<OneToManyDemo.Models.ViewModels.BoekAuteurViewModel>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Titel)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.AuteurNaam)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Titel)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AuteurNaam)
            </td>
            @* <td>
                <a asp-action="Edit" asp-route-id="@item.BoekId">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.BoekId">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.BoekId">Delete</a>
            </td> *@
        </tr>
}
    </tbody>
</table>

OneToManyDemo/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

OneToManyDemo/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - OneToManyDemo</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/OneToManyDemo.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-info bg-info border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">OneToManyDemo</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
                <form class="d-flex" role="search">
                    <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-success" type="submit">Search</button>
                </form>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - OneToManyDemo - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>